# simple.gocd.yaml
pipelines:
  pipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/davified/email-classification.git
    stages:
      - test:
          jobs:
            unit_tests: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: echo "running unit tests" && ls -la