pipelines:
  test_and_deploy:
    group: email-classification
    materials:
      git:
        git: https://github.com/davified/email-classification.git
    stages:
      - test:
          jobs:
            unit_tests:
              tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                  - ./bin/run_unit_tests.sh
