pipelines:
  test_and_deploy:
    group: email-classification
    materials:
      email-classification-git:
        git: https://github.com/davified/email-classification.git
    stages:
      - test:
          jobs:
            unit_tests:
              tasks:
               - exec:
                   command: bash
                   arguments:
                   - echo "hello gocd"
