---

galaxy_info:
  author:
    - Wojtek Oledzki
    - David Reed
    - Hagen Kuehn
  description: Install the Go Continuous Delivery server.
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  categories:
    - development
    - cd

dependencies:
  - role: sansible.users_and_groups
#    users_and_groups:
#      users:
#        - name: "{{ gocd_server.user }}"
#          gecos: Go CD user
#      groups:
#        - name: "{{ gocd_server.user }}"
#      sudoers:
#        - name: wheel
#          user: "%wheel"
#          runas: "ALL=(ALL)"
#          commands: "NOPASSWD: ALL"
#      whitelist_groups:
#        - admins

  - role: sansible.java
    java:
      version: "{{ gocd_server.java_version }}"
      vendor: oracle
    when: not gocd_server.dependencies.skip_java

