- name: Install GO CD Server and Agent
  become: true
  hosts: gocd

#  pre_tasks:
#    - name: Update apt
#      command: apt-get update -y
#      tags:
#        - build

  roles:
    - sansible.gocd_server
    - sansible.gocd_agent
